---
development:
  dialect: postgres
  database: keylogger_data
  user: keylogger_user
  password: SuperPassword123
  connect: true
  host: 127.0.0.1
  port: 5432
  name: "development"

development-read-only:
  dialect: postgres
  database: keylogger_data
  user: keylogger_user
  password: SuperPassword123
  connect: true
  host: 127.0.0.1
  port: 5432
  name: "devRO" 


development-mysql:
  dialect: mysql 
  database: keylogger_data
  user: keylogger_user
  password: SuperPassword123
  connect: true
  host: 127.0.0.1
  port: 5432
  name: "devRO" 