---
development:
  dialect: postgres
  database: tinyorm
  user: tiny 
  password: password123!
  connect: true
  host: 127.0.0.1
  port: 5432
  name: "development"
  maxIdleTime: 60 # setting connection values 
  maxLifetime: 100
  maxIdleConn: 0
  maxOpenConn: 10

development-read-only:
  dialect: postgres
  database: tinyorm
  user: tiny
  password: password123!
  connect: true
  host: 127.0.0.1
  port: 5432
  name: "devRO" 


development-mysql:
  dialect: mysql 
  database: tinyorm
  user: tiny
  password: password123!
  connect: false 
  host: 127.0.0.1
  port: 3306
  name: "devRO" 

# Simple test of SQLITE3
development-sqlite:
  dialect: sqlite3
  path: ./tinyorm.db

#  Test of SQLITE3 with Aut
development-sqlite-auth:
  dialect: sqlite3
  path: ./tinyorm.db
  auth: true
  user: tiny
  password: password123!