
version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'tinyorm'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'tiny'
      # You can use whatever password you like
      POSTGRES_PASSWORD: 'password123!'
    ports:
      # <Port exposed> : < Postgresql Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 5432 on the container
      - '5432'
      # Where our data will be persisted
    #volumes:
    #   - tinydata:/var/lib/postgresql/data

# Names our volume
# volumes:
#   tinydata:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /var/tmp/tinydata